<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/recipes/">Recipes</a></li>
    <li class="breadcrumb-item active">Ingredients</li>
  </ol>
</div>
<div class="container-fluid container-fixed-lg bg-white">
	<div class="card card-transparent">
		<div class="card-header">
			<div class="card-title">
				<h6 class="font-montserrat data-tables-header inline"></h6>
				<a href="/ingredients/add" class="btn btn-primary btn-cons pull-right btn-sm">+ Add Ingredient</a>
			</div>
		</div>
		<div class="card-body">
			<div class="table-responsive">
				<div class="dataTables_wrapper no-footer" id="basicTable_wrapper">
					<table class="table full-width" id="ingsTable">
						<thead>
							<tr>
								<th>Name</th>
								<th>Category</th>
							</tr>
						</thead>
						<tbody>
							
						</tbody>
					</table>
				</div>
				
			</div>
		</div>
	</div>
</div>