<body class="wac software jira-software hide-x-scroll-main jira" data-headerless-path="/wac/software/jira" id="jira">
	<header class="header header--wac">
		<div class="global-nav--wac">
			<div class="global-nav--wac__background">
				<div class="global-nav--wac__row">
					<div class="nav--left">
						<div class="global-nav--wac__logo">
							<a href="/"><img alt="Atlassian logo" class="lozad" src="https://wac-cdn.atlassian.com/dam/jcr:616e6748-ad8c-48d9-ae93-e49019ed5259/Atlassian-horizontal-blue-rgb.svg?cdnVersion=949"></a> <a class="global-nav--wac__back-arrow" href="#">Back</a> <span class="global-nav--wac__title"></span>
						</div>
						<div class="global-nav--wac__links">
							<div class="global-nav--wac__link has-dropdown">
								<a data-dropdown-id="dropdown-b7fc3020" href="#">Products</a>
							</div>
							<div class="global-nav--wac__link has-dropdown">
								<a data-dropdown-id="dropdown-f1867a5d" href="#">For teams</a>
							</div>
							<div class="global-nav--wac__link has-dropdown">
								<a data-dropdown-id="dropdown-6e70f9b2" href="#">Support</a>
							</div>
						</div>
						<div class="global-nav--wac__mobile-links">
							<ul>
								<li>
									<a class="support--mobile" href="/company">Support</a>
								</li>
							</ul>
							<ul class="headerless-nav--mobile-links">
								<li>
									<a class="view-all--mobile" href="/software">View all products</a>
								</li>
								<li>
									<a class="home--mobile" href="/">Atlassian.com</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="nav--right">
						<div class="global-nav--wac__buttons">
							<div class="global-nav--wac__button">
								<a class="global-nav--wac__button--secondary" href="https://www.atlassian.com/purchase/product/jira-software">Buy now</a>
							</div>
						</div><a class="global-nav--wac__search-icon" href="#">Search</a> <a class="global-nav--wac__menu-toggle" href="#">Toggle menu</a>
						<div id="global-nav--wac__container--profile"></div>
						
					</div>
				</div>
			</div>
			<div class="global-nav--wac__search">
				<form action="/search" class="global-nav--wac__search-form" method="get">
					<div class="global-nav--wac__search-container">
						<div class="global-nav--wac__search-input-container">
							<label>Search atlassian.com</label> <input autocomplete="off" class="global-nav--wac__search-input" name="q" placeholder="Search" type="text">
						</div><input class="global-nav--wac__search-submit" type="submit" value="Search"> <a class="global-nav--wac__search-close" href="#">Close search</a>
					</div>
				</form>
			</div>
			<div class="container--nav-dropdown show-ctas--mobile columns-0" id="dropdown-b7fc3020">
				<div class="container--nav-dropdown__content">
					<div class="container--nav-dropdown__columns">
						<div class="container--nav-dropdown__columns--primary">
							<div class="container--nav-dropdown__column-wrapper">
								<div class="columns-3">
									<div class="container--nav-dropdown__column--primary">
										<div class="">
											<h2>Plan, Track, &amp; Support</h2><a class="" href="/software/jira">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:826c97dc-1f5c-4955-bfcc-ea17d6b0c095/jira%20software-icon-gradient-blue.svg?cdnVersion=949" width="30"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Jira Software</h4>
													<p class="subtext--small">Project and issue tracking</p>
												</div>
											</div></a> <a class="" href="/software/jira/align">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:56de7ac6-4303-4d6a-be71-a618c353743c/Jira%20Align-icon-blue-rgb.svg?cdnVersion=949" width="22"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Jira Align</h4>
													<p class="subtext--small">Enterprise agile planning</p>
												</div>
											</div></a> <a class="" href="/software/jira/core">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:f89f1ce5-60f1-47c2-b9f5-657de4940d31/jira%20core-icon-gradient-blue.svg?cdnVersion=949" width="30"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Jira Core</h4>
													<p class="subtext--small">Essential business management</p>
												</div>
											</div></a> <a class="" href="/software/jira/service-desk">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:8e0905be-0ee7-4652-ba3a-4e3db1143969/jira%20service%20desk-icon-gradient-blue.svg?cdnVersion=949" width="30"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Jira Service Desk</h4>
													<p class="subtext--small">Collaborative IT service management</p>
												</div>
											</div></a> <a class="" href="/software/opsgenie">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:e274e162-69db-4baa-b8b3-4ca2b2d2a23b/opsgenie-icon-gradient-blue.svg?cdnVersion=949" width="30"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Opsgenie</h4>
													<p class="subtext--small">Modern incident management</p>
												</div>
											</div></a> <a class="" href="/software/statuspage">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:3c4aa48b-8422-4257-8136-7e954c254e70/statuspage-icon-gradient-blue.svg?cdnVersion=949" width="30"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Statuspage</h4>
													<p class="subtext--small">Incident communication</p>
												</div>
											</div></a>
										</div>
									</div>
									<div class="container--nav-dropdown__column--primary">
										<div class="">
											<h2>Collaborate</h2><a class="" href="/software/confluence">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:5d1374c2-276f-4bca-9ce4-813aba614b7a/confluence-icon-gradient-blue.svg?cdnVersion=949" width="30"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Confluence</h4>
													<p class="subtext--small">Document collaboration</p>
												</div>
											</div></a> <a class="" href="/software/trello">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:b6faa16c-69fe-44d8-8605-beb08c70c7bf/trello-icon-gradient-blue.svg?cdnVersion=949" width="30"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Trello</h4>
													<p class="subtext--small">Collaborate visually on any project</p>
												</div>
											</div></a>
											<div class="component--header-title horizontal-align-padding-top" style=":;">
												<h2 class="h2">Code, Build, &amp; Ship</h2>
											</div><a class="" href="/software/bitbucket">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:bf39fc40-3871-491f-98e3-fb2293f57a00/bitbucket-icon-gradient-blue.svg?cdnVersion=949" width="30"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Bitbucket</h4>
													<p class="subtext--small">Git code management</p>
												</div>
											</div></a> <a class="" href="/software/sourcetree">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:c754c38d-3efc-4d9b-a63d-daa7884dbb63/sourcetree-icon-gradient-blue.svg?cdnVersion=949" width="30"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Sourcetree</h4>
													<p class="subtext--small">Git and Mercurial desktop client</p>
												</div>
											</div></a> <a class="" href="/software/bamboo">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:560a991e-c0e3-4014-bd7d-2e65d4e4c84a/bamboo-icon-gradient-blue.svg?cdnVersion=949" width="30"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Bamboo</h4>
													<p class="subtext--small">Integration and release management</p>
												</div>
											</div></a>
										</div>
									</div>
									<div class="container--nav-dropdown__column--primary">
										<div class="spacing-fix">
											<h2>SECURITY &amp; IDENTITY</h2><a class="" href="/software/access">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:6acca3ae-b2f6-42a3-b1c0-9e809ab26b4e/atlassian-icon-gradient-blue.svg?cdnVersion=949" width="30"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Atlassian Access</h4>
													<p class="subtext--small">Security and control for cloud</p>
												</div>
											</div></a> <a class="" href="/software/crowd">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__logo-wrapper">
													<div class="container--nav-dropdown__logo" style="height: 30px;"><img class="lozad" height="30" src="https://wac-cdn.atlassian.com/dam/jcr:d2a1da52-ae52-4b06-9ab1-da8647a89653/crowd-icon-gradient-blue.svg?cdnVersion=949" width="30"></div>
												</div>
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Crowd</h4>
													<p class="subtext--small">User management for self-managed environments</p>
												</div>
											</div></a>
										</div>
									</div>
								</div>
							</div><a class="container--nav-dropdown__link--all" href="/software">View all products</a>
						</div>
						<div class="container--nav-dropdown__column--divider"></div>
						<div class="container--nav-dropdown__columns--secondary">
							<div class="container--nav-dropdown__column--secondary side">
								<div class="container--nav-dropdown__links--primary">
									<ul>
										<li class="cic">
											<a class="" href="https://marketplace.atlassian.com/">
											<h4>Marketplace</h4>
											<p>Apps that enhance Atlassian products</p></a>
										</li>
										<li class="cic pad-bottom">
											<a class="" href="http://developer.atlassian.com/">
											<h4>Developers</h4>
											<p>Docs and resources to build Atlassian apps</p></a>
										</li>
										<li class="cic hr pad-bottom hide-tablet">
											<a class="" href="https://www.atlassian.com/blog">
											<h4>Work Life Blog</h4>
											<p>Stories on culture, tech, teams, and tips</p></a>
										</li>
										<li class="cic hr">
											<a class="" href="/trust">
											<h4>Trust &amp; Security</h4>
											<p>Compliance, privacy, platform roadmap, and more</p></a>
										</li>
									</ul>
								</div><a class="container--nav-dropdown__close">Close dropdown</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container--nav-dropdown columns-0" id="dropdown-f1867a5d">
				<div class="container--nav-dropdown__content">
					<div class="container--nav-dropdown__columns">
						<div class="container--nav-dropdown__columns--primary">
							<div class="container--nav-dropdown__column-wrapper">
								<div class="columns-3">
									<div class="container--nav-dropdown__column--primary">
										<div class="">
											<h2>By team size</h2><a class="" href="/software/startups">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Startups</h4>
													<p class="subtext--small">Great for startups, from incubator to IPO</p>
												</div>
											</div></a> <a class="" href="/software/small-business">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Small business</h4>
													<p class="subtext--small">Get the right tools for your growing business</p>
												</div>
											</div></a> <a class="" href="/enterprise">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Enterprise</h4>
													<p class="subtext--small">Learn how we make big teams successful</p>
												</div>
											</div></a>
										</div>
									</div>
									<div class="container--nav-dropdown__column--primary">
										<div class="">
											<h2>By team function</h2><a class="" href="/teams/software">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Software</h4>
													<p class="subtext--small">Plan, build, &amp; ship quality products</p>
												</div>
											</div></a> <a class="" href="/teams/marketing">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Marketing</h4>
													<p class="subtext--small">Bring together a winning strategy</p>
												</div>
											</div></a> <a class="" href="/teams/hr">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">HR</h4>
													<p class="subtext--small">Streamline people management</p>
												</div>
											</div></a> <a class="" href="/teams/legal">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Legal</h4>
													<p class="subtext--small">Operate securely and reliably</p>
												</div>
											</div></a>
										</div>
									</div>
									<div class="container--nav-dropdown__column--primary">
										<div class="column--title-free">
											<a class="" href="/teams/operations">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Operations</h4>
													<p class="subtext--small">Run your business efficiently</p>
												</div>
											</div></a> <a class="" href="/teams/it">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">IT</h4>
													<p class="subtext--small">Provide great service and support</p>
												</div>
											</div></a> <a class="" href="/teams/finance">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Finance</h4>
													<p class="subtext--small">Simplify all finance processes</p>
												</div>
											</div></a> <a class="" href="/solutions/incident-management">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Incident Response</h4>
													<p class="subtext--small">Respond, resolve, &amp; learn from incidents</p>
												</div>
											</div></a>
										</div>
									</div>
								</div>
							</div><a class="container--nav-dropdown__link--all" href="/software">View all products</a>
						</div>
						<div class="container--nav-dropdown__column--divider"></div>
						<div class="container--nav-dropdown__columns--secondary">
							<div class="container--nav-dropdown__column--secondary side">
								<div class="container--nav-dropdown__links--primary">
									<ul>
										<li class="cic">
											<a class="" href="https://marketplace.atlassian.com/">
											<h4>Marketplace</h4>
											<p>Apps that enhance Atlassian products</p></a>
										</li>
										<li class="cic pad-bottom">
											<a class="" href="http://developer.atlassian.com/">
											<h4>Developers</h4>
											<p>Docs and resources to build Atlassian apps</p></a>
										</li>
										<li class="cic hr pad-bottom hide-tablet">
											<a class="" href="https://www.atlassian.com/blog">
											<h4>Work Life Blog</h4>
											<p>Stories on culture, tech, teams, and tips</p></a>
										</li>
										<li class="cic hr">
											<a class="" href="/trust">
											<h4>Trust &amp; Security</h4>
											<p>Compliance, privacy, platform roadmap, and more</p></a>
										</li>
									</ul>
								</div><a class="container--nav-dropdown__close">Close dropdown</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container--nav-dropdown columns-0" id="dropdown-6e70f9b2">
				<div class="container--nav-dropdown__content">
					<div class="container--nav-dropdown__columns">
						<div class="container--nav-dropdown__columns--primary">
							<div class="container--nav-dropdown__column-wrapper">
								<div class="columns-3">
									<div class="container--nav-dropdown__column--primary">
										<div class="">
											<h2>Atlassian support</h2><a class="" href="https://support.atlassian.com/">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Technical support</h4>
													<p class="subtext--small">Raise a support ticket</p>
												</div>
											</div></a> <a class="" href="/licensing/purchase-licensing">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Purchasing &amp; licensing</h4>
													<p class="subtext--small">Help on pricing or your account</p>
												</div>
											</div></a> <a class="" href="https://confluence.atlassian.com/display/ALLDOC/Atlassian+Documentation">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Documentation</h4>
													<p class="subtext--small">Guides to all of our products</p>
												</div>
											</div></a> <a class="" href="/cloud-migration">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Migrate to cloud</h4>
													<p class="subtext--small">Plan a migration from server to cloud</p>
												</div>
											</div></a> <a class="" href="/enterprise/services">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Enterprise services</h4>
													<p class="subtext--small">Support for large teams</p>
												</div>
											</div></a>
										</div>
									</div>
									<div class="container--nav-dropdown__column--primary">
										<div class="">
											<h2>Community support</h2><a class="" href="https://community.atlassian.com">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Community help</h4>
													<p class="subtext--small">Get help from other users</p>
												</div>
											</div></a> <a class="" href="/partners">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Partner Program</h4>
													<p class="subtext--small">Learn about Atlassian Partners</p>
												</div>
											</div></a> <a class="" href="https://partnerdirectory.atlassian.com">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Find a Partner</h4>
													<p class="subtext--small">Custom Professional Services</p>
												</div>
											</div></a>
										</div>
									</div>
									<div class="container--nav-dropdown__column--primary">
										<div class="">
											<h2>Learn &amp; connect</h2><a class="" href="/company">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">About us</h4>
													<p class="subtext--small">Learn about our company</p>
												</div>
											</div></a> <a class="" href="/company/careers">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Careers</h4>
													<p class="subtext--small">Search our latest job openings</p>
												</div>
											</div></a> <a class="" href="/university">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Training &amp; Certification</h4>
													<p class="subtext--small">Build your skills and get endorsed by Atlassian</p>
												</div>
											</div></a> <a class="sl_class" href="https://www.atlassian.com/blog">
											<div class="container--nav-dropdown__link">
												<div class="container--nav-dropdown__link-text">
													<h4 class="h4">Blogs</h4>
													<p class="subtext--small">Thought leadership on all topics</p>
												</div>
											</div></a>
										</div>
									</div>
								</div>
							</div><a class="container--nav-dropdown__link--all" href="https://support.atlassian.com">View all support</a>
						</div>
						<div class="container--nav-dropdown__column--divider"></div>
						<div class="container--nav-dropdown__columns--secondary">
							<div class="container--nav-dropdown__column--secondary side">
								<div class="container--nav-dropdown__links--primary">
									<ul>
										<li class="cic">
											<a class="" href="https://marketplace.atlassian.com/">
											<h4>Marketplace</h4>
											<p>Apps that enhance Atlassian products</p></a>
										</li>
										<li class="cic pad-bottom">
											<a class="" href="http://developer.atlassian.com/">
											<h4>Developers</h4>
											<p>Docs and resources to build Atlassian apps</p></a>
										</li>
										<li class="cic hr pad-bottom hide-tablet">
											<a class="" href="https://www.atlassian.com/blog">
											<h4>Work Life Blog</h4>
											<p>Stories on culture, tech, teams, and tips</p></a>
										</li>
										<li class="cic hr">
											<a class="" href="/trust">
											<h4>Trust &amp; Security</h4>
											<p>Compliance, privacy, platform roadmap, and more</p></a>
										</li>
									</ul>
								</div><a class="container--nav-dropdown__close">Close dropdown</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<main>
		<nav class="imkt-navbar imkt-navbar__default imkt-sticky">
			<div class=" container-fluid imkt-navbar__main-section">
				<div class="row">
					<div class="column nav-comp-column">
						<div class="imkt-navbar__title-wrapper">
							<a class="imkt-navbar__title-link" href="/software/jira"><img alt="Jira Software" class="lozad imkt-navbar__title-logo" height="23px" src="https://wac-cdn.atlassian.com/dam/jcr:e348b562-4152-4cdc-8a55-3d297e509cc8/Jira%20Software-blue.svg?cdnVersion=949"></a> <button class="aui-icon aui-icon-small aui-iconfont-arrow-down" id="jsToggleNavbarMenu">Open and close the navigation menu</button>
						</div>
						<ul class="imkt-navbar__link-list">
							<li>
								<a class="imkt-navbar__link-list-link" href="/software/jira/features">Features</a>
							</li>
							<li>
								<a class="imkt-navbar__link-list-link" href="/software/jira/guides">Product guide</a>
							</li>
							<li>
								<a class="imkt-navbar__link-list-link" href="/software/jira/enterprise">Enterprise</a>
							</li>
							<li>
								<a class="imkt-navbar__link-list-link" href="/software/jira/pricing">Pricing</a>
							</li>
						</ul>
						<div class="imkt-navbar__right-nav">
							<a class="component__link button button--one button--small button--secondary button--primary__on-stuck" href="/software/jira/free">Try it free</a>
						</div>
					</div>
				</div>
			</div>
			<div class="container-fluid imkt-navbar__collapsed-section">
				<div class="row">
					<div class="column">
						<ul class="imkt-navbar__collapsed-link-list">
							<li>
								<a class="imkt-navbar__collapsed-link-list-link" href="/software/jira/features">Features</a>
							</li>
							<li>
								<a class="imkt-navbar__collapsed-link-list-link" href="/software/jira/guides">Product guide</a>
							</li>
							<li>
								<a class="imkt-navbar__collapsed-link-list-link" href="/software/jira/enterprise">Enterprise</a>
							</li>
							<li>
								<a class="imkt-navbar__collapsed-link-list-link" href="/software/jira/pricing">Pricing</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</nav>
		<div class="container-fluid xs-none-bottom wcf-201–control">
			<div class="row flex-container">
				<div class="column column-md-5 column-lg-4 column-lg-offset-1 vertical-middle">
					<div class="component component--heading">
						<h1 class="heading">The #1 software development tool used by agile teams</h1>
					</div>
					<div class="component component--block xs-compact-top">
						<div class="component component--link-button">
							<a class="component__link button button--one button--regular button--primary" href="/software/jira/free">Try it free</a>
						</div>
					</div>
				</div>
				<div class="column column-md-7 xs-none-bottom vertical-bottom">
					<div class="component component--image" style="transform-origin:top;"><img alt="Illustration" class="lozad component__image" id="f3877e6f" src="https://wac-cdn.atlassian.com/dam/jcr:b86a32cb-0aa8-4783-aa81-9592d4fbf829/jsw-header-illustrations---v3.png?cdnVersion=949"></div>
				</div>
			</div>
		</div>
		<div class="container-fluid xs-compact n20">
			<div class="row flex-container reduced-row">
				<div class="column column-md-3 column-xs-8 column-md-offset-0 column-xs-offset-2">
					<div class="component component--image"><img alt="Upcoming announcement" class="lozad component__image" id="a5afd868" src="https://wac-cdn.atlassian.com/dam/jcr:3ac53ac2-d859-41b9-99d2-33b75c9a805d/introducing-roadmaps.svg?cdnVersion=949"></div>
				</div>
				<div class="column column-md-8 vertical-middle">
					<div class="component component--heading-textblock">
						<h3 class="heading">See how we’re reimagining Jira Software Cloud</h3>
						<p>Roadmaps, new boards, and easier configuration are just the beginning.</p>
					</div>
					<div class="component component--link-button">
						<a class="component__link button button--one button--small button--secondary" href="/software/jira/next-gen">Take a look</a>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid md-cozy wcf-201–control">
			<div class="row">
				<div class="column column-md-11 column-lg-8 column-md-offset-1 column-lg-offset-2 text-center">
					<div class="component component--heading-textblock text-oversized">
						<h2 class="heading">The best software teams ship early and often.</h2>
						<p>Jira Software is built for every member of your software team to plan,<br>
						track, and release great software.</p>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid xs-compact-bottom md-comfortable-bottom">
			<div class="row flex-container">
				<div class="column column-md-7 column-md-inset-1 column-lg-inset-0 vertical-middle">
					<div class="component component--image image-depth"><img alt="Backlog" class="lozad component__image" id="013a94c6" src="https://wac-cdn.atlassian.com/dam/jcr:8e2b794f-0d62-4b16-ab23-7810bfd4ce66/Group%205.png?cdnVersion=949"></div>
				</div>
				<div class="column column-lg-4 column-md-6 vertical-middle">
					<div class="component component--block xs-cozy-bottom">
						<div class="component component--heading-textblock text-oversized">
							<h3 class="heading">Plan</h3>
							<p>Create user stories and issues, plan sprints, and distribute tasks across your software team.</p>
						</div>
					</div>
					<div class="component component--block">
						<div class="component component--heading-textblock text-oversized">
							<h3 class="heading">Track</h3>
							<p>Prioritize and discuss your team&rsquo;s work in full context with complete visibility.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid xs-cozy-bottom md-outerspace-bottom">
			<div class="row flex-container">
				<div class="column column-md-7 column-lg-push-5 column-md-push-6 vertical-middle">
					<div class="component component--image image-depth"><img alt="Releases" class="lozad component__image" id="46dcbe70" src="https://wac-cdn.atlassian.com/dam/jcr:ed5a5006-c1e0-4c56-b22c-4ab8533fd29d/plan-track.png?cdnVersion=949"></div>
				</div>
				<div class="column column-lg-4 column-md-6 column-lg-pull-6 column-md-pull-0 column-md-inset-7 column-lg-inset-0 vertical-middle">
					<div class="component component--block xs-cozy-bottom">
						<div class="component component--heading-textblock text-oversized">
							<h3 class="heading">Release</h3>
							<p>Ship with confidence and sanity knowing the information you have is always up-to-date.</p>
						</div>
					</div>
					<div class="component component--block">
						<div class="component component--heading-textblock text-oversized">
							<h3 class="heading">Report</h3>
							<p>Improve team performance based on real-time, visual data that your team can put to use.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid md-comfortable md-compact-bottom wcf-201–control n0">
			<div class="row flex-container">
				<div class="column column-md-5 column-lg-4 column-md-offset-1 column-lg-offset-2 xs-none-bottom md-compact-bottom vertical-middle">
					<div class="component component--heading">
						<h2 class="heading">Choose a workflow, or make your own</h2>
					</div>
				</div>
				<div class="column column-md-5 column-lg-4 vertical-middle">
					<div class="component component--textblock text-oversized">
						<p>Every team has a unique process for shipping software. Use an out-of-the-box workflow, or create one to match the way your team works.</p>
					</div>
				</div>
				<div class="column column-md-10 column-lg-8 column-md-offset-1 column-lg-offset-2 lg-outerspace lg-outerspace md-comfortable sm-cozy hide-xs hide-sm text-center">
					<div class="imkt-animation" id="uuid-f4d1135d-dbf9-4178-ba5a-a3533b755911">
						<img alt="Animation placeholder" class="lozad" id="uuid-f4d1135d-dbf9-4178-ba5a-a3533b755911-image" src="https://wac-cdn.atlassian.com/dam/jcr:6203a73b-f2a1-4d91-9587-bc4b7d822d6b/workflow_timeline_desktop-temporary.svg?cdnVersion=949"> 
					</div>
				</div>
				<div class="column column-md-10 column-lg-8 column-md-offset-1 column-lg-offset-2 hide-md hide-lg hide-xl text-center">
					<div class="component component--image"><img alt="Workflow" class="lozad component__image" id="b78b9ced" src="https://wac-cdn.atlassian.com/dam/jcr:a18b549d-48e8-4132-a242-cbe50e67da85/workflow_timeline_mobile.svg?cdnVersion=949" style="width:300px;"></div>
				</div>
				<div class="column column-lg-8 column-md-10 column-lg-offset-2 column-md-offset-1 text-center">
					<div class="component component--heading-textblock text-oversized">
						<h2 class="heading">Integrate with the tools you already use</h2>
						<p>Upgrade your workflow with Confluence, Bitbucket, and hundreds of other developer tools.</p>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid md-cozy-bottom wcf-201–control n0">
			<div class="row reduced-row">
				<div class="column column-md-6 column-lg-4">
					<div class="component component--image-heading-textblock">
						<div class="component__image"><img alt="Icon" class="lozad component__image xs-comfortable-bottom" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:cd0479fa-ce91-412a-86e8-abcd2362d5bb/software%20jira%20documentation%20confluence.svg?cdnVersion=949" style="height:66px;"></div>
						<div class="component__heading-textblock">
							<h4 class="heading">Knowledge management</h4>
							<p>Transform product requirements in Confluence into a Jira Software backlog with one click.</p>
						</div>
					</div>
					<div class="component component--link-button">
						<a class="component__link link-arrow" href="/software/confluence">Learn more about Confluence<svg class="link-arrow-image" height="8px" version="1.1" viewbox="0 0 11 8" width="11px" xmlns="http://www.w3.org/2000/svg">
						<g fill="none" fill-rule="evenodd" stroke="none" stroke-width="1">
							<g class="group-path" fill="#0052CC" transform="translate(-138.000000, -586.000000)">
								<path d="M145.2803,586.507862 L144.2193,587.568863 L145.9393,589.287862 L138.7503,589.287862 C138.3363,589.287862 138.0003,589.623862 138.0003,590.037862 C138.0003,590.451862 138.3363,590.787862 138.7503,590.787862 L145.9393,590.787862 L144.2193,592.507862 L145.2803,593.568863 L148.8103,590.037862 L145.2803,586.507862 Z" id="Fill-1"></path>
							</g>
						</g></svg></a>
					</div>
				</div>
				<div class="column column-md-6 column-lg-4">
					<div class="component component--image-heading-textblock">
						<div class="component__image"><img alt="Icon" class="lozad component__image xs-comfortable-bottom" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:033e6808-6753-4ebe-a579-8aeca167c743/Software-Git.svg?cdnVersion=949" style="height:66px;"></div>
						<div class="component__heading-textblock">
							<h4 class="heading">Development workflow</h4>
							<p>Jira Software automatically updates issues and transitions work when code is committed in Bitbucket.</p>
						</div>
					</div>
					<div class="component component--link-button">
						<a class="component__link link-arrow" href="/software/bitbucket">Learn more about Bitbucket<svg class="link-arrow-image" height="8px" version="1.1" viewbox="0 0 11 8" width="11px" xmlns="http://www.w3.org/2000/svg">
						<g fill="none" fill-rule="evenodd" stroke="none" stroke-width="1">
							<g class="group-path" fill="#0052CC" transform="translate(-138.000000, -586.000000)">
								<path d="M145.2803,586.507862 L144.2193,587.568863 L145.9393,589.287862 L138.7503,589.287862 C138.3363,589.287862 138.0003,589.623862 138.0003,590.037862 C138.0003,590.451862 138.3363,590.787862 138.7503,590.787862 L145.9393,590.787862 L144.2193,592.507862 L145.2803,593.568863 L148.8103,590.037862 L145.2803,586.507862 Z" id="Fill-1"></path>
							</g>
						</g></svg></a>
					</div>
				</div>
				<div class="column column-md-6 column-lg-4">
					<div class="component component--image-heading-textblock">
						<div class="component__image"><img alt="Icon" class="lozad component__image xs-comfortable-bottom" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:40d95e12-b2cc-4c19-a0e9-dadef3053949/Software-Hierarchy%20Window.svg?cdnVersion=949" style="height:66px;"></div>
						<div class="component__heading-textblock">
							<h4 class="heading">Continuous integration and deployment</h4>
							<p>Supercharge&nbsp;your CI/CD&nbsp;with Pipelines and monitor build status&nbsp;from within Jira Software.</p>
						</div>
					</div>
					<div class="component component--link-button">
						<a class="component__link link-arrow" href="https://bitbucket.org/product/features/pipelines">Learn more about Pipelines<svg class="link-arrow-image" height="8px" version="1.1" viewbox="0 0 11 8" width="11px" xmlns="http://www.w3.org/2000/svg">
						<g fill="none" fill-rule="evenodd" stroke="none" stroke-width="1">
							<g class="group-path" fill="#0052CC" transform="translate(-138.000000, -586.000000)">
								<path d="M145.2803,586.507862 L144.2193,587.568863 L145.9393,589.287862 L138.7503,589.287862 C138.3363,589.287862 138.0003,589.623862 138.0003,590.037862 C138.0003,590.451862 138.3363,590.787862 138.7503,590.787862 L145.9393,590.787862 L144.2193,592.507862 L145.2803,593.568863 L148.8103,590.037862 L145.2803,586.507862 Z" id="Fill-1"></path>
							</g>
						</g></svg></a>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid md-comfortable n20">
			<div class="row flex-container">
				<div class="column column-lg-2 column-md-3 column-xs-8 column-lg-offset-2 column-md-offset-1 column-xs-offset-2 text-center vertical-middle">
					<div class="component component--image"><img alt="Automation spot" class="lozad component__image" id="c734f376" src="https://wac-cdn.atlassian.com/dam/jcr:bfa903cc-b4ce-4f69-97e8-8dd557eb9e1d/automation-spot.svg?cdnVersion=949"></div>
				</div>
				<div class="column column-lg-6 column-md-7 vertical-middle">
					<div class="component component--heading-textblock text-oversized">
						<h2 class="heading">Deliver value faster</h2>
						<p>Save time, do more and integrate your tools with Jira automation.&nbsp;</p>
					</div>
					<div class="component component--link-button">
						<a class="component__link link-arrow" href="/software/jira/features/automation">Learn more about automation<svg class="link-arrow-image" height="8px" version="1.1" viewbox="0 0 11 8" width="11px" xmlns="http://www.w3.org/2000/svg">
						<g fill="none" fill-rule="evenodd" stroke="none" stroke-width="1">
							<g class="group-path" fill="#0052CC" transform="translate(-138.000000, -586.000000)">
								<path d="M145.2803,586.507862 L144.2193,587.568863 L145.9393,589.287862 L138.7503,589.287862 C138.3363,589.287862 138.0003,589.623862 138.0003,590.037862 C138.0003,590.451862 138.3363,590.787862 138.7503,590.787862 L145.9393,590.787862 L144.2193,592.507862 L145.2803,593.568863 L148.8103,590.037862 L145.2803,586.507862 Z" id="Fill-1"></path>
							</g>
						</g></svg></a>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid md-compact-top md-cozy-bottom">
			<div class="row flex-container">
				<div class="column column-lg-6 column-md-8 column-lg-offset-3 column-md-offset-2 md-comfortable-bottom md-cozy-top text-center">
					<div class="component component--heading-textblock">
						<h2 class="heading">Designed for security and scale</h2>
						<p>Gain peace of mind with enterprise-grade solutions tailor-made&nbsp;to secure and scale Jira Software across your entire organization.</p>
					</div>
				</div>
				<div class="column column-lg-4 column-md-6 column-lg-offset-2 column-md-offset-0 md-comfortable-bottom">
					<div class="component component--image-heading-textblock">
						<div class="component__image"><img alt="Control tower illustration" class="lozad component__image md-outerspace-bottom" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:fd487e90-1e57-4412-9c23-5fb20f30ae07/Access%20module%20image-01.svg?cdnVersion=949"></div>
						<div class="component__heading-textblock">
							<h2 class="heading">Atlassian Access</h2>
							<p>Sleep soundly with enhanced administration and security backed by SAML SSO, enforced 2-step verification, automated user provisioning, and more.</p>
						</div>
					</div>
					<div class="component component--link-button">
						<a class="component__link link-arrow" href="/software/access">Learn more<svg class="link-arrow-image" height="8px" version="1.1" viewbox="0 0 11 8" width="11px" xmlns="http://www.w3.org/2000/svg">
						<g fill="none" fill-rule="evenodd" stroke="none" stroke-width="1">
							<g class="group-path" fill="#0052CC" transform="translate(-138.000000, -586.000000)">
								<path d="M145.2803,586.507862 L144.2193,587.568863 L145.9393,589.287862 L138.7503,589.287862 C138.3363,589.287862 138.0003,589.623862 138.0003,590.037862 C138.0003,590.451862 138.3363,590.787862 138.7503,590.787862 L145.9393,590.787862 L144.2193,592.507862 L145.2803,593.568863 L148.8103,590.037862 L145.2803,586.507862 Z" id="Fill-1"></path>
							</g>
						</g></svg></a>
					</div>
				</div>
				<div class="column column-lg-4 column-md-6 md-comfortable-bottom">
					<div class="component component--image-heading-textblock">
						<div class="component__image"><img alt="Atlassian Premium illustration" class="lozad component__image md-outerspace-bottom" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:8ebe2a91-8722-4bb9-8b36-07b0177bdf88/Premium%20Cloud%20module%20image.svg?cdnVersion=949"></div>
						<div class="component__heading-textblock">
							<h2 class="heading">Jira Software Premium</h2>
							<p>Ensure your team and organization are ready to&nbsp;scale with&nbsp;99.9% uptime SLAs, unlimited storage,&nbsp;24x7 Premium Support, and more.</p>
						</div>
					</div>
					<div class="component component--link-button">
						<a class="component__link link-arrow" href="/software/jira/premium">Learn more<svg class="link-arrow-image" height="8px" version="1.1" viewbox="0 0 11 8" width="11px" xmlns="http://www.w3.org/2000/svg">
						<g fill="none" fill-rule="evenodd" stroke="none" stroke-width="1">
							<g class="group-path" fill="#0052CC" transform="translate(-138.000000, -586.000000)">
								<path d="M145.2803,586.507862 L144.2193,587.568863 L145.9393,589.287862 L138.7503,589.287862 C138.3363,589.287862 138.0003,589.623862 138.0003,590.037862 C138.0003,590.451862 138.3363,590.787862 138.7503,590.787862 L145.9393,590.787862 L144.2193,592.507862 L145.2803,593.568863 L148.8103,590.037862 L145.2803,586.507862 Z" id="Fill-1"></path>
							</g>
						</g></svg></a>
					</div>
				</div>
				<div class="column column-lg-10 column-md-12 column-lg-offset-1 column-md-offset-0">
					<div class="container-fluid">
						<div class="row flex-container">
							<div class="column column-md-4">
								<div class="component component--image-heading-textblock">
									<div class="component__image"><img alt="Fingerprint" class="lozad component__image" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:5fc4019a-9fd4-4571-a754-ee3a33b8cc14/PRIVACY@2x.png?cdnVersion=949" style="height:36px;"></div>
									<div class="component__heading-textblock">
										<h4 class="heading">Privacy</h4>
										<p>Jira Software invested in&nbsp;<a href="/trust/privacy">GDPR and Privacy Shield</a>&nbsp;to ensure all data is handled with&nbsp;care.</p>
									</div>
								</div>
							</div>
							<div class="column column-md-4">
								<div class="component component--image-heading-textblock">
									<div class="component__image"><img alt="Two keys" class="lozad component__image" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:d7803d4b-80d4-4fb8-a358-b971f497d3ef/DATAENCRYPTION@2x.png?cdnVersion=949" style="height:36px;"></div>
									<div class="component__heading-textblock">
										<h4 class="heading">Data Encryption</h4>
										<p>Jira Software leverages&nbsp;<a href="https://www.atlassian.com/trust/security/security-practices#faq-5fd9f2cf-d7c7-40fa-af1f-854e2d9f3f48">encryption in transit and at rest</a>&nbsp;to safeguard your organization&#39;s&nbsp;data.</p>
									</div>
								</div>
							</div>
							<div class="column column-md-4">
								<div class="component component--image-heading-textblock">
									<div class="component__image"><img alt="Shield with checkmark" class="lozad component__image" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:8864d1c9-fa84-47f8-806b-e58b733e5689/icons-security-shield%20check-dark-60x72@2x.png?cdnVersion=949" style="height:36px;"></div>
									<div class="component__heading-textblock">
										<h4 class="heading">Compliance</h4>
										<p>Verify Jira Software&#39;s security&nbsp;with <a href="/trust/compliance">SOC2, SOC3, ISO 27001, ISO 27018, PCI DSS, and more</a>.</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="column column-md-6 column-md-offset-3 md-cozy text-center">
					<div class="component component--horizontal-rule align-center">
						<hr class="default">
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid md-cozy-top container--marketplace wcf-201–control" data-container-id="1ee0c5d1-7522-4b65-9b21-58c15813d36b">
			<style>
			[data-container-id="1ee0c5d1-7522-4b65-9b21-58c15813d36b"] { background-image: url("https://wac-cdn.atlassian.com/dam/jcr:ae6a494b-edfe-484f-a106-4539e348377b/marketplace%20section-update.svg?cdnVersion=949") ; background-position: bottom ; background-repeat: no-repeat ; background-size: auto ; } 
			</style>
			<div class="row flex-container">
				<div class="column column-xl-2 column-md-3 column-sm-3 column-xl-offset-2 column-lg-offset-1 text-center vertical-middle">
					<div class="component component--image"><img alt="Icon" class="lozad component__image" id="c5669d85" src="https://wac-cdn.atlassian.com/dam/jcr:5ea2fadd-0605-4c16-a464-a85e342f5918/build-atlassian.png?cdnVersion=949" style="width:192px;"></div>
				</div>
				<div class="column column-xl-6 column-lg-7 column-md-9 column-sm-9 md-comfortable-bottom vertical-middle">
					<div class="component component--heading-textblock text-oversized">
						<h2 class="heading">Extend Jira Software with apps</h2>
						<p><a href="/software/jira/portfolio">Portfolio for Jira</a>, Tempo Timesheets, Zephyr, and over 3,000 other apps ensure Jira Software can be custom tailored&nbsp;to fit any and every use case.</p>
					</div>
					<div class="component component--link-button">
						<a class="component__link link-arrow" href="https://marketplace.atlassian.com/addons/app/jira#">Explore apps on Atlassian Marketplace<svg class="link-arrow-image" height="8px" version="1.1" viewbox="0 0 11 8" width="11px" xmlns="http://www.w3.org/2000/svg">
						<g fill="none" fill-rule="evenodd" stroke="none" stroke-width="1">
							<g class="group-path" fill="#0052CC" transform="translate(-138.000000, -586.000000)">
								<path d="M145.2803,586.507862 L144.2193,587.568863 L145.9393,589.287862 L138.7503,589.287862 C138.3363,589.287862 138.0003,589.623862 138.0003,590.037862 C138.0003,590.451862 138.3363,590.787862 138.7503,590.787862 L145.9393,590.787862 L144.2193,592.507862 L145.2803,593.568863 L148.8103,590.037862 L145.2803,586.507862 Z" id="Fill-1"></path>
							</g>
						</g></svg></a>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid md-comfortable-top n30">
			<div class="row">
				<div class="column column-md-10 column-xl-8 column-md-offset-1 column-xl-offset-2 wcf-201–control text-center">
					<div class="column__background n0">
						<div class="component component--image"><img alt="Jira Software mobile app" class="lozad component__image" id="1112a14c" src="https://wac-cdn.atlassian.com/dam/jcr:e0cedee5-a180-40ad-b7c3-a66d6e60f483/jira-app-adg3.svg?cdnVersion=949" style="width:70px;height:70px;"></div>
						<div class="component component--heading-textblock text-oversized" style="max-width:600px;margin:0 auto;">
							<h2 class="heading">Move work forward from anywhere</h2>
							<p>Track and manage projects in real time from the convenience of your favorite device with Jira mobile.</p>
						</div>
						<div class="component component--block">
							<div class="component component--image mobile-button" style="display:inline;margin-right:10px;">
								<a class="component--image__link" href="https://itunes.apple.com/app/apple-store/id1006972087?pt=696495&amp;ct=Landing%20Page%20WAC&amp;mt=8"><img alt="App Store" class="lozad component__image" id="1071f42d" src="https://wac-cdn.atlassian.com/dam/jcr:797c71d8-f84e-425f-8183-25a9eee39453/Download_on_the_App_Store_Badge_US-UK_135x40.svg?cdnVersion=949" style="width:135px;height:40px;"></a>
							</div>
							<div class="component component--image" style="display:inline;">
								<a class="component--image__link" href="https://play.google.com/store/apps/details?id=com.atlassian.android.jira.core"><img alt="Google Play" class="lozad component__image" id="04a6bc42" src="https://wac-cdn.atlassian.com/dam/jcr:c8a73824-72f9-4f2b-ba05-b2c491b235c7/Get%20it%20on%20Google%20play%20Badge.svg?cdnVersion=949" style="width:135px;height:40px;"></a>
							</div>
						</div>
					</div>
				</div>
				<div class="component component--block customer-quote-split-column clear-all">
					<div class="container-fluid xs-none-top">
						<div class="row flex-container">
							<div class="column column-md-5 column-xl-4 column-md-offset-1 column-xl-offset-2">
								<div class="component component--image image-cover"><img alt="Trulia" class="lozad component__image" id="85aee734" src="https://wac-cdn.atlassian.com/dam/jcr:dd7fd4eb-f9fe-4047-9fff-346f6579c622/jira_trulia_customer_story.png?cdnVersion=949" style="width:1000px;height:360px;"></div>
							</div>
							<div class="column column-md-5 column-xl-4 vertical-middle">
								<div class="column__background n0">
									<div class="component component--image"><img alt="Trulia" class="lozad component__image xs-outerspace-bottom" id="0e598fc9" src="https://wac-cdn.atlassian.com/dam/jcr:1d6b77d7-21b5-4513-b38f-8debe5d9c5e6/trulia-logo.svg?cdnVersion=949" style="width:78px;height:23px;"></div>
									<div class="component component--heading-textblock component--heading-textblock--blockquote">
										<blockquote>
											<p>&ldquo;Jira Software is instrumental in building and maintaining the best software on the market.&rdquo;</p>
										</blockquote>
										<div class="quoted-from">
											DANIELE FARNEDI, TRULIA CTO
											<div class="quoted-from__info"></div>
										</div>
									</div>
									<div class="component component--link-button">
										<a class="component__link link-arrow" href="/customers/trulia">View their story<svg class="link-arrow-image" height="8px" version="1.1" viewbox="0 0 11 8" width="11px" xmlns="http://www.w3.org/2000/svg">
										<g fill="none" fill-rule="evenodd" stroke="none" stroke-width="1">
											<g class="group-path" fill="#0052CC" transform="translate(-138.000000, -586.000000)">
												<path d="M145.2803,586.507862 L144.2193,587.568863 L145.9393,589.287862 L138.7503,589.287862 C138.3363,589.287862 138.0003,589.623862 138.0003,590.037862 C138.0003,590.451862 138.3363,590.787862 138.7503,590.787862 L145.9393,590.787862 L144.2193,592.507862 L145.2803,593.568863 L148.8103,590.037862 L145.2803,586.507862 Z" id="Fill-1"></path>
											</g>
										</g></svg></a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="column column-md-10 column-lg-8 column-md-offset-1 column-lg-offset-2 text-center">
					<div class="component component--heading wcf-201–control">
						<h4 class="heading">Trusted by over 65,000 customers worldwide</h4>
					</div>
					<div class="component component--image">
						<picture class="lozad-picture component__picture"><source media="(min-width: 0px) and (max-width: 539px)" srcset="https://wac-cdn.atlassian.com/dam/jcr:05cdbe73-2ef7-4ecf-9567-b61600de4a0d/partner-logos-mobile.png?cdnVersion=949 429w"> <source srcset="https://wac-cdn.atlassian.com/dam/jcr:527cb590-de73-4de8-832e-b255d9314946/Partner-Logos.png?cdnVersion=949 2508w"> <img alt="Atlassian Partners" class="lozad component__image xs-comfortable-top" id="fac8825f" src="https://wac-cdn.atlassian.com/dam/jcr:e3a7420c-4e52-49aa-80f3-dcfe8dd205a0/Partner-Logos.png?cdnVersion=949"></picture>
					</div>
				</div>
				<div class="column column-md-10 column-md-offset-1 wcf-201–control">
					<hr>
				</div>
			</div>
		</div>
		<div class="curve-container n30">
			<svg class="curve-container__curve curve-three" viewbox="0 0 1440 68" xmlns="http://www.w3.org/2000/svg">
			<path d="m1622.3 1937.7c0 0-410.7 169.1-913.4 75.5-502.7-93.6-977.7 56.3-977.7 56.3v440h1891.1v-571.8" fill="#F4F5F7" transform="translate(0-1977)"></path></svg>
			<div class="curve-three container-fluid">
				<div class="row flex-container reduced-row">
					<div class="column column-md-8 column-md-offset-2 xs-cozy text-center">
						<div class="component component--heading">
							<h2 class="heading">Simple plans hosted in the cloud</h2>
						</div>
					</div>
					<div class="column column-md-4 column-sm-8 column-sm-offset-2 column-md-offset-0 free-block">
						<div class="component loading component--price-block-localized heading-highlighted">
							<div class="component--price-block-localized__heading localized_pricing_heading">
								<h3 class="h3 heading">Free</h3>
							</div>
							<div class="component--price-block-localized__price">
								<span class="localized_pricing_currency_code">USD</span> <span class="localized_pricing_price">X</span>
							</div>
							<div class="component--price-block-localized__primaryText localized_pricing_primary_text">
								per user/month
							</div>
							<div class="component--price-block-localized__secondaryText localized_pricing_secondary_text">
								up to 10 users
							</div>
							<div class="component--price-block-localized__button">
								<a class="component__link button button--one button--regular button--primary" data-track-properties-eventcomponent="button" data-track-properties-label="Get started" data-track-properties-magnoliacomponentid="2608f336-39ee-4170-be1d-d3b90fbc8204" data-track-properties-productkey="JIRA Software" href="/try/cloud/signup?bundle=jira-software&amp;edition=free">Get started</a>
							</div>
							<div class="component--price-block__post-cta-text first-post-cta-text--with-button">
								Free forever
							</div>
							<div class="component--price-block__post-cta-text">
								No obligation
							</div>
							<script type="text/x-component">
							{ "type":"imkt.components.PriceBlockLocalized", "params": { "productKey":"jira-software.ondemand.free", "tierStart":"0", "period":"MONTHLY" } } 
							</script>
						</div>
					</div>
					<div class="column column-md-4 column-sm-8 column-sm-offset-2 column-md-offset-0">
						<div class="component loading component--price-block-localized">
							<div class="component--price-block-localized__heading localized_pricing_heading">
								<h3 class="h3 heading">Standard</h3>
							</div>
							<div class="component--price-block-localized__price">
								<span class="localized_pricing_currency_code">USD</span> <span class="localized_pricing_price">X</span>
							</div>
							<div class="component--price-block-localized__primaryText localized_pricing_primary_text">
								per user/month
							</div>
							<div class="component--price-block-localized__secondaryText localized_pricing_secondary_text">
								11-100 users
							</div>
							<div class="component--price-block-localized__button">
								<a class="component__link button button--one button--regular button--secondary" data-track-properties-eventcomponent="button" data-track-properties-label="Start trial" data-track-properties-magnoliacomponentid="f4518b77-2a0e-469c-af50-1a3fd7ad9adb" data-track-properties-productkey="JIRA Software" href="/software/jira/try">Start trial</a>
							</div>
							<div class="component--price-block__post-cta-text first-post-cta-text--with-button">
								Free for 7 days
							</div>
							<div class="component--price-block__post-cta-text">
								No credit card needed
							</div>
							<script type="text/x-component">
							{ "type":"imkt.components.PriceBlockLocalized", "params": { "productKey":"jira-software.ondemand", "tierStart":"1", "period":"MONTHLY" } } 
							</script>
						</div>
					</div>
					<div class="column column-md-4 column-sm-8 column-sm-offset-2 column-md-offset-0">
						<div class="component loading component--price-block-localized">
							<div class="component--price-block-localized__heading localized_pricing_heading">
								<h3 class="h3 heading">Premium</h3>
							</div>
							<div class="component--price-block-localized__price">
								<span class="localized_pricing_currency_code">USD</span> <span class="localized_pricing_price">X</span>
							</div>
							<div class="component--price-block-localized__primaryText localized_pricing_primary_text">
								per user/month
							</div>
							<div class="component--price-block-localized__secondaryText localized_pricing_secondary_text">
								1-100 users
							</div>
							<div class="component--price-block-localized__button">
								<a class="component__link button button--one button--regular button--secondary" data-track-properties-eventcomponent="button" data-track-properties-label="Start trial" data-track-properties-magnoliacomponentid="ad3251ce-f66c-47b8-a950-cda53c26e888" data-track-properties-productkey="JIRA Software" href="/try/cloud/signup?bundle=jira-software&amp;edition=premium">Start trial</a>
							</div>
							<div class="component--price-block__post-cta-text first-post-cta-text--with-button">
								Free for 7 days
							</div>
							<div class="component--price-block__post-cta-text">
								No credit card needed
							</div>
							<div class="component--price-block__post-cta-text">
								<a href="https://www.atlassian.com/software/jira/premium">Learn more</a>
							</div>
							<script type="text/x-component">
							{ "type":"imkt.components.PriceBlockLocalized", "params": { "productKey":"jira-software.ondemand.premium", "tierStart":"0", "period":"MONTHLY" } } 
							</script>
						</div>
					</div>
					<div class="column card-theme-tight text-center">
						<div class=" block-theme-one">
							<div class="component component--textblock">
								<p><strong>101+ users?</strong> &nbsp; We offer discounts for large teams! <a href="https://www.atlassian.com/software/jira/pricing#pricing-calculator">Calculate your price</a></p>
							</div>
						</div>
					</div>
					<div class="column column-md-8 column-md-offset-2 xs-cozy-top md-compact-top md-cozy-bottom text-center">
						<div class="component component--link-button">
							<a class="component__link default" href="/software/jira/download">Want to host on your own server?</a>
						</div>
					</div>
					<div class="column column-md-10 column-md-offset-1 xs-comfortable">
						<hr>
					</div>
					<div class="column column-md-8 column-lg-6 column-md-offset-2 column-lg-offset-3 text-center">
						<div class="component component--heading-textblock text-oversized">
							<h2 class="heading">Go agile with ease</h2>
							<p>Whether you&rsquo;re a seasoned agile expert, or just getting started, Jira Software unlocks the power of agile.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid md-comfortable-bottom wcf-201–control">
			<div class="row flex-container reduced-row">
				<div class="column column-sm-6 column-md-4">
					<div class="component component--image-heading-textblock">
						<div class="component__image"><img alt="Icon" class="lozad component__image" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:f7f91d46-4ce9-4955-bcdb-2967d9a5e9aa/organize-workflow.svg?cdnVersion=949" style="width:42px;height:42px;"></div>
						<div class="component__heading-textblock">
							<h3 class="heading">Flexible planning</h3>
							<p>Scrum? Check. Kanban? Check. Mixed methodology? Check. Jira Software&rsquo;s rich planning features enable your team to flexibly plan in a way that works best for them.</p>
						</div>
					</div>
				</div>
				<div class="column column-sm-6 column-md-4">
					<div class="component component--image-heading-textblock">
						<div class="component__image"><img alt="Icon" class="lozad component__image" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:73199416-ccfe-4f9b-84b2-570b401a7870/chart-line.svg?cdnVersion=949" style="width:42px;height:42px;"></div>
						<div class="component__heading-textblock">
							<h3 class="heading">Accurate estimations</h3>
							<p>Estimations help your team become more accurate and efficient. Use story points, hours, t-shirt sizes, or your own estimation technique. Jira Software supports them all.</p>
						</div>
					</div>
				</div>
				<div class="column column-sm-6 column-md-4">
					<div class="component component--image-heading-textblock">
						<div class="component__image"><img alt="Icon" class="lozad component__image" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:135905fd-33ad-4cd7-adf0-02f93fcbadb6/finance-dollar%20dotted.svg?cdnVersion=949" style="width:42px;height:42px;"></div>
						<div class="component__heading-textblock">
							<h3 class="heading">Value-driven prioritization</h3>
							<p>Order user stories, issues, and bugs in your product backlog with simple drag and drop prioritization. Ensure stories that deliver the most customer value are always at the top.</p>
						</div>
					</div>
				</div>
				<div class="column column-sm-6 column-md-4">
					<div class="component component--image-heading-textblock">
						<div class="component__image"><img alt="Icon" class="lozad component__image" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:c656d0c9-53d1-413a-ae75-54c9f93d70b9/transparent%20icon.svg?cdnVersion=949" style="width:42px;height:42px;"></div>
						<div class="component__heading-textblock">
							<h3 class="heading">Transparent execution</h3>
							<p>Whether your team is across the table or around the world, Jira Software brings a new level of transparency to your team&#39;s work and keeps everyone on the same page.</p>
						</div>
					</div>
				</div>
				<div class="column column-sm-6 column-md-4">
					<div class="component component--image-heading-textblock">
						<div class="component__image"><img alt="Icon" class="lozad component__image" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:0f07dc8d-04b9-43a2-b9d9-75d68b686a5b/status-check.svg?cdnVersion=949" style="width:42px;height:42px;"></div>
						<div class="component__heading-textblock">
							<h3 class="heading">Actionable results</h3>
							<p>Extensive reporting functionality gives your team critical insight into their agile process. Backed by data, retrospectives are more data-driven and actionable than ever before.</p>
						</div>
					</div>
				</div>
				<div class="column column-sm-6 column-md-4">
					<div class="component component--image-heading-textblock">
						<div class="component__image"><img alt="Icon" class="lozad component__image" id="info.magnolia.context.HTMLEscapingWebContextWrapper@625dab73" src="https://wac-cdn.atlassian.com/dam/jcr:90691311-2ab1-41ff-ae98-a1ef782c5a96/organize-expand.svg?cdnVersion=949" style="width:42px;height:42px;"></div>
						<div class="component__heading-textblock">
							<h3 class="heading">Scalable evolution</h3>
							<p>Add and change issue types, fields, and workflows as your team evolves. Jira Software is agile project management designed for teams of every shape and size.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</main>
	<footer class="footer footer--wac" id="footer">
		<div class="container-fluid xs-none-bottom n20">
			<div class="container-fluid xs-none-top footer-links">
				<div class="row">
					<div class="column column-lg-2 column-lg-offset-1">
						<div class="component component--image">
							<a class="component--image__link" href="/"><img alt="Atlassian" class="lozad component__image" id="1bdd15c9" src="https://wac-cdn.atlassian.com/dam/jcr:bec8148d-b7dc-493f-bbba-7519b0637581/logos-atlassian-logo-gradient-horizontal-neutral.svg?cdnVersion=949" style="width:125px;"></a>
						</div>
					</div>
					<div class="column column-md-3 column-lg-2 column-xs-6">
						<div class="component component--heading">
							<h3 class="h5 heading">Products</h3>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/software/jira">Jira Software</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/software/jira/align">Jira Align</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/software/jira/service-desk">Jira Service Desk</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/software/confluence">Confluence</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="https://www.trello.com/home">Trello</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/software/bitbucket">Bitbucket</a>
						</div>
						<div class="component component--link-button footer-view-all">
							<a class="component__link default" href="/software">View all products</a>
						</div>
					</div>
					<div class="column column-md-3 column-lg-2 column-xs-6">
						<div class="component component--heading">
							<h3 class="h5 heading">Resources</h3>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="https://support.atlassian.com/">Technical Support</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/licensing/purchase-licensing">Purchasing &amp; licensing</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="https://community.atlassian.com">Atlassian Community</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="https://confluence.atlassian.com/kb">Knowledge base</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="https://marketplace.atlassian.com/">Marketplace</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="https://my.atlassian.com/products/index">My Account</a>
						</div>
						<div class="component component--link-button footer-view-all">
							<a class="component__link default" href="https://support.atlassian.com/contact/">Create support ticket</a>
						</div>
					</div>
					<div class="column column-md-3 column-lg-2 column-xs-6">
						<div class="component component--heading">
							<h3 class="h5 heading">Expand &amp; Learn</h3>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/partners">Partners</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/university">Training &amp; Certification</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="https://confluence.atlassian.com/display/ALLDOC/Atlassian+Documentation">Documentation</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="https://developer.atlassian.com/">Developer Resources</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/licensing/purchase-licensing">Purchasing FAQ</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/enterprise/services">Enterprise services</a>
						</div>
						<div class="component component--link-button footer-view-all">
							<a class="component__link default" href="/resources">View all resources</a>
						</div>
					</div>
					<div class="column column-md-3 column-lg-2 column-xs-6">
						<div class="component component--heading">
							<h3 class="h5 heading">About Atlassian</h3>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/company">Company</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/company/careers">Careers</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/company/events">Events</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="https://www.atlassian.com/blog">Blogs</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="https://investors.atlassian.com/">Investor Relations</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/trust">Trust &amp; Security</a>
						</div>
						<div class="component component--link-button footer-view-all">
							<a class="component__link default" href="/company/contact">Contact us</a>
						</div>
					</div>
				</div>
			</div>
			<div class="container-fluid xs-none footer--wac__copyright">
				<div class="row">
					<div class="column column-lg-10 column-lg-offset-1 flex-container">
						<div class="language-selector">
							<a class="language-selector--text" href="#">Languages</a>
							<form action="#" method="get">
								<select name="url">
									<option disabled selected>
										Choose your language
									</option>
									<option aria-label="Deutsch" class="notranslate SL_opaque" data-lang="de" label="Deutsch" value="https://www.atlassian.com/de/software/jira">
										Deutsch
									</option>
									<option aria-label="English" class="notranslate SL_opaque" data-lang="en" label="English" value="https://www.atlassian.com/software/jira">
										English
									</option>
									<option aria-label="&#268;e&#353;tina" class="notranslate SL_opaque" data-lang="cs" label="&#268;e&#353;tina" value="https://www.atlassian.com/cs/software/jira">
										&#268;e&#353;tina
									</option>
									<option aria-label="Espa&#241;ol" class="notranslate SL_opaque" data-lang="es" label="Espa&#241;ol" value="https://www.atlassian.com/es/software/jira">
										Español
									</option>
									<option aria-label="Fran&#231;ais" class="notranslate SL_opaque" data-lang="fr" label="Fran&#231;ais" value="https://www.atlassian.com/fr/software/jira">
										Français
									</option>
									<option aria-label="Italiano" class="notranslate SL_opaque" data-lang="it" label="Italiano" value="https://www.atlassian.com/it/software/jira">
										Italiano
									</option>
									<option aria-label="한국어" class="notranslate SL_opaque" data-lang="ko" label="한국어" value="https://www.atlassian.com/ko/software/jira">
										한국어
									</option>
									<option aria-label="Magyar" class="notranslate SL_opaque" data-lang="hu" label="Magyar" value="https://www.atlassian.com/hu/software/jira">
										Magyar
									</option>
									<option aria-label="Nederlands" class="notranslate SL_opaque" data-lang="nl" label="Nederlands" value="https://www.atlassian.com/nl/software/jira">
										Nederlands
									</option>
									<option aria-label="&#26085;&#26412;&#35486;" class="notranslate SL_opaque" data-lang="ja" label="&#26085;&#26412;&#35486;" value="https://www.atlassian.com/ja/software/jira">
										日本語
									</option>
									<option aria-label="Polski" class="notranslate SL_opaque" data-lang="pl" label="Polski" value="https://www.atlassian.com/pl/software/jira">
										Polski
									</option>
									<option aria-label="Portugu&#234;s" class="notranslate SL_opaque" data-lang="br" label="Portugu&#234;s" value="https://www.atlassian.com/br/software/jira">
										Português
									</option>
									<option aria-label="Suomi" class="notranslate SL_opaque" data-lang="fi" label="Suomi" value="https://www.atlassian.com/fi/software/jira">
										Suomi
									</option>
									<option aria-label="&#1088;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;" class="notranslate SL_opaque" data-lang="ru" label="&#1088;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;" value="https://www.atlassian.com/ru/software/jira">
										русский
									</option>
									<option aria-label="&#20013;&#25991;" class="notranslate SL_opaque" data-lang="zh" label="&#20013;&#25991;" value="https://www.atlassian.com/zh/software/jira">
										&#20013;&#25991;
									</option>
								</select> 
								<script type="text/x-component">
								{ "type":"imkt.common.LanguageSelector", "params": { } } 
								</script>
							</form>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/legal/privacy-policy">Privacy policy</a>
						</div>
						<div class="component component--link-button">
							<a class="component__link default" href="/legal/cloud-terms-of-service">Terms</a>
						</div>
						<div class="component component--copyright">
							<p>Copyright &copy; 2020 Atlassian</p>
						</div>
						<div class="imkt-social-buttons-group">
							<div class="imkt-social-buttons standard">
								<ul>
									<li class="imkt-social-button social-code facebook">
										<a href="https://www.facebook.com/Atlassian" title="Atlassian on Facebook"></a>
									</li>
									<li class="imkt-social-button social-code twitter">
										<a href="https://twitter.com/atlassian" title="Follow us on Twitter"></a>
									</li>
									<li class="imkt-social-button social-code linked-in">
										<a href="https://www.linkedin.com/company/atlassian" title="Atlassian on LinkedIn"></a>
									</li>
									<li class="imkt-social-button social-code youtube">
										<a href="https://www.youtube.com/user/GoAtlassian" title="Atlassian on YouTube"></a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>