<div class="card share" data-social="item">

  <div class="card-description p-t-20">
    <div class="row text-center">

      <div style="background-color: #2583e4;width: 100%;height: 50px;position: absolute;z-index: 0;left: 0;top: 0;">
      </div>

      <div class="inline" style="display: inline!important;margin: 0 auto;z-index: 2;">
        <div class="thumbnail-wrapper d80 circular bordered b-white text-center" style="margin: 0 auto;">
          <img alt="Avatar" width="55" height="55" data-src-retina="/uploads/eddy/profile.jpg" data-src="/uploads/eddy/profile.jpg" src="/uploads/eddy/profile.jpg">
        </div>
        <br>
        <i class="fa fa-check-circle text-success fs-16 m-t-10"></i>
        <p class="fs-15 bold"> Anubir Singh</p>
      </div>
      
    </div>
  </div>

</div>