<div class="col-lg-4 sm-p-b-10">
			<div class="card social-card share  full-width m-b-10 no-border" id="companyforcasted">
      <div class="card-body no-padding">
         <ul class="nav nav-tabs nav-tabs-simple m-b-20" role="tablist" data-init-reponsive-tabs="collapse">
            <li class="nav-item text-black">
                <a href="#unpaid" class="active" class="" data-toggle="tab" role="tab" aria-expanded="true" aria-selected="false">
                    <span id="unpaid-total" class="bold fs-15"></span> Unpaid Orders
                </a>
            </li>
            <li class="nav-item">
                <a href="#pending" data-toggle="tab" role="tab" aria-expanded="false" aria-selected="true">
                    <span id="upcoming-total" class="bold fs-15"></span> Upcoming Events
                </a>
            </li>
         </ul>
         <div class="tab-content no-padding" style="max-height: 400px; overflow-y: auto;">
            <div class="tab-pane active no-padding" id="unpaid">
               
                <table id="table-unpaid" class="table" style="width: 100%;">
                    <thead></thead>
                    <tbody></tbody>
                </table><a href="#" class="btn btn-block">See Orders</a>

            </div>
            <div class="tab-pane no-padding" id="pending">
               
               <table id="table-upcoming" class="table" style="width: 100%;">
                   <thead></thead>
                   <tbody></tbody>
               </table><a href="#" class="btn btn-block">See Orders</a>

            </div>
         </div>
      </div>
   </div>
</div>

<div class="col-lg-4 sm-p-b-10">
	<div class="card social-card share  full-width m-b-10 no-border">
        <div class="card-body no-padding">
        <ul class="nav nav-tabs nav-tabs-simple m-b-20" role="tablist" data-init-reponsive-tabs="collapse">
            <li class="nav-item text-black">
                <a href="#pieChart" class="active" class="" data-toggle="tab" role="tab" aria-expanded="true" aria-selected="false">
                    Ingredient Usage
                </a>
            </li>
            <li class="nav-item">
                <a href="#horizBar" data-toggle="tab" role="tab" aria-expanded="false" aria-selected="true">
                    Popular Recipes
                </a>
            </li>
         </ul>

         <div class="tab-content no-padding" style="min-height: 400px; overflow-y: auto;">
            <div class="tab-pane active no-padding" id="pieChart">
               
            </div>
            <div class="tab-pane no-padding" id="horizBar">
            
            </div>
         </div>

        </div>
   </div>
</div>