<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/settings/">Settings</a></li>
    <li class="breadcrumb-item active">Users</li>
  </ol>
</div>
<div class="container-fluid container-fixed-lg bg-white">
	<div class="card card-transparent">
		<div class="card-header">
			<div class="card-title">
				<h6 class="font-montserrat data-tables-header inline"></h6>
				<a href="/settings/add-user/" class="btn btn-primary btn-cons pull-right btn-sm">+ Add User</a>
			</div>
		</div>
		<div class="card-body">
			<div class="table-responsive">
				<div class="dataTables_wrapper no-footer" id="basicTable_wrapper">
					<table class="table" id="usersTable" role="grid">
						<thead>
							<tr role="row">
								<!-- <th></th> -->
								<th>Name</th>
								<th>Username</th>
								<th>Email</th>
								<th>Active</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>