<!-- START APP -->
  <!-- START SECONDARY SIDEBAR MENU-->
  <nav class="secondary-sidebar light">
    <div class=" m-b-30 m-l-30 m-r-30 d-sm-none d-md-block d-lg-block d-xl-block">
      <button id="btn-compose" class="btn btn-primary btn-block text-white"><i class="flaticon flaticon-plus-symbol"></i>Compose</button>
    </div>
    <p class="menu-title">BROWSE</p>
    <ul class="main-menu">
      <li class="active">
        <a href="#" data-mail-menu="inbox">
          <span class="title"><i class="flaticon flaticon-inbox"></i> Inbox</span>
          <span class="badge pull-right">5</span>
        </a>
      </li>
      <li>
        <a href="#" data-mail-menu="sent">
          <span class="title"><i class="flaticon flaticon-outbox"></i> Sent</span>
        </a>
      </li>
      <li>
        <a href="#" data-mail-menu="trash">
          <span class="title"><i class="flaticon flaticon-garbage"></i> Trash</span>
        </a>
      </li>
      <!-- <li>
        <a href="#">
          <span class="title"><i class="pg-spam"></i> Spam</span>
          <span class="badge pull-right">10</span>
        </a>
      </li> -->
    </ul>
    <!-- <p class="menu-title m-t-20 all-caps">Quick view</p>
    <ul class="sub-menu no-padding">
      <li>
        <a href="#">
          <span class="title">Documents</span>
        </a>
      </li>
      <li>
        <a href="#">
          <span class="title">Flagged</span>
          <span class="badge pull-right">5</span>
        </a>
      </li>
      <li>
        <a href="#">
          <span class="title">Images</span>
        </a>
      </li>
    </ul> -->
  </nav>
  <!-- END SECONDARY SIDEBAR MENU -->
  <div class="inner-content full-height">

    <?php $this->render('email-composer'); ?>
    <?php $this->render('split-view'); ?>

  </div>
  <!-- END APP -->