<div class="split-view">
  <!-- START SPLIT LIST VIEW -->
  <div class="split-list">
    <a class="list-refresh" href="#"><i class="fa fa-refresh"></i></a>
    <div data-email="list" class=" boreded no-top-border">
      <!-- START EMAIL LIST SORTED BY DATE -->
      <ul class="no-padding no-margin"></ul>
      <!-- END EMAIL LIST SORTED BY DATE -->
    </div>
  </div>
  <!-- END SPLIT LIST VIEW -->
  <!-- START SPLIT DETAILS -->
  <div data-email="opened" class="split-details">
    <div class="no-result">
      <h1>No email has been selected</h1>
    </div>
    <div class="email-content-wrapper" style="display:none">
      <div class="actions-wrapper menuclipper bg-master-lightest">
        <ul class="actions menuclipper-menu no-margin p-l-20 ">
          <li class="d-lg-none d-xl-none sm-no-padding">
            <a href="#" class="split-list-toggle"><i class="flaticon flaticon-left-chevron"></i> All Inboxes</a>
          </li>
          <li class="no-padding ">
            <a href="#" class="text-info">Reply</a>
          </li>
          <li class="no-padding ">
            <a href="#" class="text-danger">Delete</a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="email-content" id="emailContent">
        <div class="email-content-header">
          <div class="thumbnail-wrapper d48 circular bordered">
            <img width="40" height="40" alt="" data-src-retina="assets/img/profiles/avatar2x.jpg" data-src="assets/img/profiles/avatar.jpg" src="assets/img/profiles/avatar2x.jpg">
          </div>
          <div class="sender inline m-l-10">
            <p class="name no-margin bold">
            </p>
            <p class="datetime no-margin"></p>
          </div>
          <div class="clearfix"></div>
          <div class="subject m-t-20 m-b-20 semi-bold"></div>
        </div>
        <div class="hr"></div>
        <div class="email-content-body m-t-20">
        </div>
        <div class="email-content-replies m-t-20"></div>
      </div>
    </div>
  </div>
  <!-- END SPLIT DETAILS -->
  <!-- START COMPOSE BUTTON FOR TABS -->
  <div class="compose-wrapper d-md-none">
    <a class="compose-email text-info pull-right m-r-10 m-t-10" href="email_compose.html"><i class="fa fa-pencil-square-o"></i></a>
  </div>
  <!-- END COMPOSE BUTTON -->
</div>