<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">Invoices</li>
  </ol>
</div>
<div class="container-fluid container-fixed-lg bg-white">
  <div class="card card-transparent">
    <div class="card-header">
      <div class="card-title">
        <h6 class="font-montserrat data-tables-header inline"></h6>
      </div>
    </div>
    <div class="alert alert-danger" role="alert">
      <button class="close" data-dismiss="alert"></button>
      <strong>NOTE:</strong> Invoices are only meant for private events. Private events are events that have been prepaid for, and are invoiced by the client as they have a set order.
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <div class="dataTables_wrapper no-footer" id="basicTable_wrapper">
          <table class="table full-width" id="invoiceTable">
            <thead>
              <tr>
                <th>Invoice ID</th>
                <th>Date</th>
                <th>Client</th>
                <th>Status</th>
                <th>Total Recipes</th>
                <th>Net Total</th>
                <th>Paid</th>
              </tr>
            </thead>
            <tbody>
              
            </tbody>
          </table>
        </div>
        
      </div>
    </div>
  </div>
</div>