<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/admin/">Admin</a></li>
    <li class="breadcrumb-item active">Create User</li>
  </ol>
</div>
<div class="container-xs-height error-page">
  <div class="row-xs-height">
    <div class="col-xs-height">
      <div class="col-md-12">
        <h4 class="text-center m-t-10">Add <span class="semi-bold">New User</span></h4>
        <div class="error-container-innner">
          <form action="<?=$_SERVER['REQUEST_URI'];?>" id="form-add-user" method="post" autocomplete="off">
            <div class="form-group">
              <label>First Name</label>
              <input type="text" id="firstname" name="firstname" autocomplete="off" class="form-control">
            </div>
            <div class="form-group">
              <label>Last Name</label>
              <input type="text" id="lastname" name="lastname" autocomplete="off" class="form-control">
            </div>
            <div class="form-group">
              <label>Email</label>
              <input type="email" id="email" name="email" autocomplete="off" class="form-control">
            </div>
            <div class="form-group">
              <label>Username</label>
              <input type="text" id="username" name="username" autocomplete="off" class="form-control">
            </div>
            <div class="form-group">
              <label>Password</label>
              <input type="password" id="password" name="password" autocomplete="off" class="form-control">
            </div>
            <div class="form-group xs-pt-10">
              <button type="submit" class="btn btn-block btn-primary btn-xl">Create</button>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>