<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">Admin</li>
  </ol>
</div>
<div class="container-fluid container-fixed-lg bg-white">
	<div class="card card-transparent">
		<div class="card-header">
			<div class="card-title">
				<h6 class="font-montserrat data-tables-header inline"></h6>
				<a href="/admin/add-company" class="btn btn-primary btn-cons pull-right btn-sm"><i class="fa fa-plus"></i>  Add Company</a>
			</div>
		</div>
		<div class="card-body">
			<div class="table-responsive">
				<div class="dataTables_wrapper no-footer" id="basicTable_wrapper">
					<table class="table" id="compsTable">
						<thead>
							<tr>
								<th>Name</th>
								<th>Address</th>
								<th>Phone</th>
								<th class="text-center">Active</th>
							</tr>
						</thead>
						<tbody>
							
						</tbody>
					</table>
				</div>
				
			</div>
		</div>
	</div>
</div>