<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/admin">Admin</a></li>
    <li class="breadcrumb-item active">Login</li>
  </ol>
</div>
<div class="container-xs-height full-height error-page">
  <div class="row-xs-height">
    <div class="col-middle">
      <div class="col-md-12">
        <h4 class="text-center m-t-10">Admin <span class="semi-bold">Login</span></h4>
        <div class="error-container-innner">
          <form action="<?=$_SERVER['REQUEST_URI'];?>" id="form-login" method="post" autocomplete="off">
            <div class="form-group">
              <label>Username</label>
              <input type="text" id="username" name="username" autocomplete="off" class="form-control">
            </div>
            <div class="form-group">
              <label>Password</label>
              <input type="password" id="password" name="password" autocomplete="off" class="form-control">
            </div>
            <div class="form-group xs-pt-10">
              <button type="submit" class="btn btn-block btn-primary btn-xl">Create</button>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>