<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active">Sales</li>
  </ol>
</div>
<div class="container-fluid container-fixed-lg bg-white">
  <div class="card card-transparent">
    <div class="card-header">
      <div class="card-title">
        <h6 class="font-montserrat data-tables-header inline"></h6>
      </div>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <div class="dataTables_wrapper no-footer" id="basicTable_wrapper">
          <table class="table full-width" id="salesTable">
            <thead>
              <tr>
                <th>Invoice ID</th>
                <th>Date</th>
                <th>Client</th>
                <th>Event Type</th>
                <th>Total Recipes</th>
                <th>Net Total</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              
            </tbody>
          </table>
        </div>
        
      </div>
    </div>
  </div>
</div>