<div class="container-xs-height full-height error-page">
  <div class="row-xs-height">
    <div class="col-xs-height col-middle">
      <div class="col-md-12">
        <h2 class="semi-bold text-center">Register</h2>
        <div class="error-container-innner">
          <form action="<?=$_SERVER['REQUEST_URI'];?>" id="register-form" method="post" autocomplete="off">
            <div class="row signup">
              <div class="col-sm-6">
                <div class="form-group form-group-default required" aria-required="true">
                  <label>First Name</label>
                  <input id="fname" name="fname" type="text" placeholder="First Name"  required="" class="form-control" autofill="off">
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group form-group-default required" aria-required="true">
                  <label>Last Name</label>
                  <input id="lname" name="lname" type="text" placeholder="Last Name" class="form-control" autofill="off" required>
                </div>
              </div>
            </div>
            <div class="form-group form-group-default">
              <label>Username</label>
              <input type="text" id="username" name="username" required="" placeholder="Username" autocomplete="off" class="form-control">
            </div>
            <input type="hidden" name="type" id="user-type" value="player">
            <?php 
            /*<div class="form-group form-group-default intermediary-types hidden">
              <select name="user-type" id="user-type">
                <option value="">Select Intermediary Type</option>
                <option value="scout">Scout</option>
                <option value="agent">Agent</option>
                <option value="coach">Coach</option>
              </select>
            </div>*/
            ?>
            <div class="form-group form-group-default">
              <label>Email</label>
              <input type="email" id="email" name="email" required="" placeholder="E-mail" autocomplete="off" class="form-control">
            </div>
            <div class="form-group form-group-default signup-password">
              <label>Password</label>
              <input id="password" name="password" type="password" placeholder="Enter Password"  required="" class="form-control" autofill="off">
            </div>
            <div class="form-group form-group-default signup-password">
              <label>Confirm Password</label>
              <input type="password" name="password_confirm" placeholder="Enter Password"  required="" class="form-control" autofill="off">
            </div>
            <div class="form-group xs-pt-10">
              <button type="submit" class="btn btn-block btn-primary btn-xl">Sign Up</button>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>