<script>
var ingredientsArr = <?=json_encode($this->recipe['ingredients']);?>;
</script>

<div class="container-xs-height full-height error-page">
  <div class="row-xs-height">
    <div class="col-xs-height col-middle">
      <div class="col-md-12">
        <h4 class="text-center m-t-10">Edit <span class="semi-bold"><?=$this->recipe['name'];?></span></h4>
        <div class="error-container-innner">
          <div class="alert alert-info" role="alert">
            <button class="close" data-dismiss="alert"></button>
            <strong>NOTE: </strong>You cannot change the name of arecipe as all names are required for historicals.  <br/>If you feel you have made a <strong>MISTAKE</strong>, please <strong>ARCHIVE</strong> this and create a new recipe.
          </div>
          <form action="<?=$_SERVER['REQUEST_URI'];?>" id="form-create-recipe" method="post" autocomplete="off">
            <input type="hidden" id="ingredientsArray" name="ingredientsArray" value='<?=json_encode($this->recipe['ingredients']);?>'>
            <div class="form-group">
              <label>Name</label>
              <input type="text" id="name" name="name" required="" autocomplete="off" class="form-control" value="<?=$this->recipe['name'];?>">
            </div>
            <div class="form-group">
              <label>Description</label>
              <input type="text" id="description" name="description" required="" autocomplete="off" class="form-control" value="<?=$this->recipe['description'];?>">
            </div>
            <div class="form-group">
              <label>Category</label>
              <input type="text" id="category" name="category" required="" autocomplete="off" class="form-control" value="<?=$this->recipe['category'];?>">
            </div>
            <div class="form-group">
              <label>Ingredients</label><br/>
              <div id="ingredient-holder">
                <?php foreach($this->recipe['ingredients'] as $key => $ing): ?>
                  <div class="block full-width p-t-5 p-b-5" style="height: 40px; <?=($key+1 < count($this->recipe['ingredients']) ? 'border-bottom: 1px dotted #CCC;' : '');?>">
                    
                    <a class="full-width ingredient-item font-montserrat fs-12 inline-block" 
                     data-ing-value="<?=$ing['name'];?>" data-ing-id="<?=$ing['id'];?>">
                      <strong class="pull-left"><?=$ing['name'];?> 
                      ($<?=$ing['ppw'];?> p/g)
                      </strong>
                      <span data-sub-recipe="35" data-recipe="13" class="remove pull-right fs-12 p-l-10 p-r-5 inline-block">
                        <i class="flaticon flaticon-round-minus"></i>
                      </span>
                    </a>
                  </div>
                <?php endforeach;?>
              </div>
              <div class="m-b-20 block">
                <select id="ingredient" class="form-control" style="width: 100%; margin-bottom:10px;">
                  <?php foreach($this->ingredients as $ing): ?>
                    <option 
                      value="<?=$ing['id'];?>" 
                      data-ppw="<?=$ing['ppw'];?>"
                      ><?=$ing['name'];?> ($<?=$ing['ppw'];?> p/g)</option>
                  <?php endforeach;?>
                </select>
                <a id="add-ingredient" class="text-white pull-right btn btn-xs btn-primary">+&nbsp;Add Ingredient</a>
                <br/>
              </div>
            </div>
            <div class="form-group xs-pt-10 text-right">
              <a href="javascript:history.go(-1)" class="btn btn-warning btn-xl text-black pull-left">Back</a>
              <button type="submit" class="btn btn-primary btn-xl">Save</button>
              <a class="btn btn-danger btn-xl text-white delete-recipe">Delete</a>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>