<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">Recipes</li>
  </ol>
</div>
<div class="container-fluid container-fixed-lg bg-white">
	<div class="card card-transparent">
		<div class="card-header">
			<div class="card-title">
				<h6 class="font-montserrat data-tables-header inline"></h6>
				<a href="/recipes/add" class="m-b-20 btn btn-primary btn-cons pull-right">+ Add Recipe</a>
			</div>
		</div>
		<div class="card-body">
			<div class="table-responsive">
				<div class="dataTables_wrapper no-footer" id="basicTable_wrapper">
					<table class="table full-width dataTable no-footer" id="recipesTable" role="grid">
						<thead>
							<tr role="row">
								<th style="width: 10px;"></th>
								<th>Name</th>
								<th>Description</th>
								<th>Category</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>